FROM python:3.10 AS webautomation


WORKDIR /TESTING/

RUN python3.10 -m venv venv 
RUN . /venv/bin/activate

RUN python -m pip install --upgrade pip

COPY requirements.txt requirements.txt
COPY . .
RUN pip3 install -r requirements.txt

CMD ["python","-m","pytest","tests/","--alluredir=reports","--host","chrome","--remote"]

