version: "3"

services:
  chrome:
    image: selenium/standalone-chrome:latest
    container_name: chrome
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "4444:4444"
      - "5900:5900"

  pytest:
    build:
      context: ./
      dockerfile: Dockerfile_pytest
    container_name: pytest
    entrypoint: [
        "python","-m","pytest",
        "--remote", "--host=chrome", "-port=4444","--alluredir=reports"
    ]    volumes:
      - ./reports:/TESTING/reports
    tty: true
