version: "3.8"

services:
  chrome:
    image: selenium/standalone-chrome:latest
    container_name: chrome
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "4444:4444"
      - "5900:5900"

  pytest:
    container_name: pytest
    build: 
      context: ./
      dockerfile: Dockerfile_pytest
    volumes:
      - ./allure-results:/TESTING/allure-results
    tty: true
