FROM python:3.10


WORKDIR /TESTING/

RUN python3.10 -m venv venv 
RUN  .\venv\bin\activate

RUN python -m pip install --upgrade pip

COPY requirements.txt requirements.txt

COPY . .

RUN pip install -r requirements.txt

CMD ["python","-m","pytest","tests","--alluredir=reports","--host","chrome","--remote"]

