version: "3"

services:
  chrome:
    image: selenium/standalone-chrome-debug:latest
    container_name: chrome
    volumes:
      - /dev/shm:/dev/shm
    networks:
      selenium_net: {}
    ports:
      - "4444:4444"
      - "5900:5900"

  pytest:
    build:
      context: ./
      dockerfile: Dockerfile_pytest
    container_name: pytest
    volumes:
      - ./allure-results:/TESTING/allure-results

    networks:
      selenium_net: {}
    tty: true

networks:
  selenium_net:
    driver: bridge

