version: "3"

services:
  chrome:
    image: selenium/standalone-chrome:latest
    container_name: chrome
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "4444:4444"
      - "5900:5900"

  pytest:
    build:
      context: ./
      dockerfile: Dockerfile_pytest
    depends_on:
      - chrome    
    container_name: pytest
    entrypoint: [ "python","-m",
        "pytest","tests","--alluredir=allure-reports",
        "--remote", "--host=chrome"
    ]    
  
    volumes:
      - ./allure-results:/TESTING/allure-results
    tty: true
