#FROM byrnedo/alpine-curl:0.1.8 as curl

#RUN curl https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh > wait-for-it.sh
FROM python:3.10

WORKDIR /TESTING/
RUN python -m pip install --upgrade pip


COPY requirements.txt requirements.txt
COPY . .
RUN pip3 install -r requirements.txt

#COPY --from=curl wait-for-it.sh wait-for-it.sh
#RUN chmod +x wait-for-it.sh

CMD ["python","-m","pytest","tests/","--alluredir=allure-results","--host","chrome","--remote", "--browser=chrome"]
