version: "3"

services:
  chrome:
    image: selenium/standalone-chrome:latest
    container_name: chrome
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "4444:4444"
      - "5900:5900"

  pytest:
    container_name: pytest
    build: 
      context: ./
      dockerfile: Dockerfile_pytest
    depends_on:
      - chrome
    entrypoint: [
        "./wait-for-it.sh", "-t", "15", "pytest",
        "--remote", "--host=chrome", "--port=4444"
    ]  
    volumes:
      - ./allure-results:/TESTING/allure-results
    tty: true
