name: Integration Tests

on:
  push:
    branches: [main]

jobs:
  Integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
     
      - name: Create docker container
        env:
          COMPOSE_INTERACTIVE_NO_CLI: 1
        run: docker compose -f "docker-compose-v2.yml" up -d
 
      - name: Check running containers
        run: docker-compose ps -a

      - name: Test with pytest
        env:
          COMPOSE_INTERACTIVE_NO_CLI: 1
        run: docker compose -f "docker-compose-v2.yml" exec pytest bash
          
      - name: Test with pytest
        env:
          COMPOSE_INTERACTIVE_NO_CLI: 1
        run: python3 -m pytest tests —host “chrome” —remote --alluredir=allure-reports

        
      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          folder: allure-history

