name: Integration Tests

on:
  push:
    branches: 
      - main
      

jobs:
  Integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create docker container and run test cases
        run: make run-all-tests-and-clean
        continue-on-error: true
        
      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          folder: allure-history
          
      
      - name: Delete container
        run: docker system prune -f --volumes
         
